#ifndef imx8qx_dcd_1_2GHz_RET_H
#define imx8qx_dcd_1_2GHz_RET_H
#define LP4_MANUAL_DERATE_WORKAROUND 
#define BD_DDR_RET 
#define BD_DDR_RET_NUM_DRC 1U
#define BD_DDR_RET_NUM_REGION 2U
#define BD_DDR_RET_REGION1_ADDR 0x80000000U
#define BD_DDR_RET_REGION1_SIZE 64U
#define BD_DDR_RET_REGION2_ADDR 0x80004040U
#define BD_DDR_RET_REGION2_SIZE 16U
#endif
